name: nightly and on.push docker builds

on:
  # to trigger manually if we really need it
  workflow_dispatch:
    inputs:
      tag_name:
        description: "the name of the tag for the docker image"
        type: "string"
        required: true

  # to trigger
  push:
    tags-ignore:
      - "bitwarden-eso-provider-*"
    paths:
      - docker/**

  schedule:
    # * is a special character in YAML so you have to quote this string
    # triggers every day at 00:00 UTC (midnight)
    - cron:  '0 0 * * *'

jobs:
  docker-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Docker Build and Push
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          # build from the ./docker directory in this repo
          context: docker
          platforms: |
            linux/amd64
          tags: |
            ${{ secrets.HARBOR_REPOSITORY }}:${{ inputs.tag_name }}

      # push with ref_name if
      - name: Docker Build and Push
        if: ${{ github.event_name != 'workflow_dispatch' && github.event_name != 'schedule' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          # build from the ./docker directory in this repo
          context: docker
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ secrets.HARBOR_REPOSITORY }}:${{ github.ref_name }}

      - name: Get most recent tag
        if: ${{ github.event_name == 'schedule' }}
        run: echo "last_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Docker Build and Push
        if: ${{ github.event_name == 'schedule' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          # build from the ./docker directory in this repo
          context: docker
          platforms: |
            linux/amd64
          tags: |
            ${{ secrets.HARBOR_REPOSITORY }}:nightly
            ${{ secrets.HARBOR_REPOSITORY }}:${{ env.last_tag }}
